streets = [
  "Rua Mauro Alves",
  "Rua Lincoln Byrro",
  "Rua S\u00edria",
  "Avenida Wenceslau Braz",
  "Rua Liberdade",
  "Avenida Ouro Preto",
  "Avenida Europa",
  "Rua 40",
  "Rua dos Can\u00e1rios",
  "Avenida Euz\u00e9bio Cabral",
  "Rua 12",
  "Rua Vila Mariquita",
  "Rua Jo\u00e3o Pereira Neves",
  "Rua Rosita Silva de Oliveira",
  "Rua Quatro - Bairro Planalto",
  "Rua Bahia",
  "Avenida Altino Marqu\u00eas",
  "Rua Dois de Fevereiro",
  "Rua H",
  "Rua 30",
  "Avenida B",
  "Rua Adrualdo Monte Alto",
  "Rua Tiradentes",
  "Rua S\u00e3o Tiago Menor",
  "Rua Monte Tauro",
  "Rua Acacias",
  "Rua Dorcelina Maria de Jesus",
  "Rua Madrid",
  "Avenida Principal",
  "Rua Flamboyante",
  "Rua Cipriano de Abreu",
  "Rua Itamar Teixeira",
  "Rua D\u00e9cima Segunda",
  "Rua Jequitib\u00e1",
  "Rua S Dois",
  "Rua Pedro Leopoldo",
  "Rua Finl\u00e2ndida",
  "Rua Martim Afonso",
  "Rua Ab\u00edlio Pato",
  "Rua das Aroeiras",
  "Rua dos Bem-Te-Vi",
  "Avenida Brasil",
  "Rua Jos\u00e9 do Patrocinio",
  "Rua Bom Despacho",
  "Rua Rio Doce",
  "Rua Lina Martello",
  "Rua Portugal",
  "Rua M\u00f3gno",
  "Rua Jo\u00e3o Sim\u00e3o",
  "Rua 15",
  "Rua Maur\u00edcio Nassau",
  "Rua Noventa e Oito",
  "Rua S\u00e3o Geraldo",
  "Rua Paineiras",
  "Rua Jos\u00e9 Tavares Pereira",
  "Rua Buenos Aires",
  "Rua 2 de Julho",
  "Rua Cento e Dezenove",
  "Avenida Jos\u00e9 Ivair Ferreira Mattos",
  "Rua S\u00e3o Felipe",
  "Rua Grevilha",
  "Rua das Hort\u00eancias",
  "Rua Vinicius de Moraes",
  "Rua Jatob\u00e1",
  "Rua C",
  "Rua Cacique",
  "Rua Verona",
  "Rua Monte Gerezim",
  "Rua Alagoas",
  "Rua Jo\u00e3o Pinheiro",
  "Rua Bela Vista",
  "Rua Jo\u00e3o Dias Duarte",
  "Avenida S\u00e3o Tom\u00e9",
  "Rua 11",
  "Rua Tupinanbas",
  "Rua Oper\u00e1rio",
  "Rua Vinte e Sete",
  "Rua Lins do R\u00eago",
  "Avenida Pascoal de Souza Lima",
  "Rua Vicente Pifano",
  "Rua das Araras",
  "Rua das Rosas",
  "Rua \u00c2ngelo Pagani",
  "Avenida It\u00e1lia",
  "Rua Ip\u00ea Preto",
  "Rua Resplendor",
  "Avenida Roma",
  "Rua Vidal Negreiro",
  "Rua Costantino \u00d4mega",
  "Rua da Justi\u00e7a",
  "Rua Mestre Jo\u00e3o Lucas",
  "Avenida Coletora C",
  "Rua T",
  "Avenida Odilon Ferreira Mattos",
  "Rua Dom Herminio",
  "Rua Frei Odorico Virga",
  "Rua 110",
  "Avenida Quatro",
  "Rua Henrique Bernadeli",
  "Rua Francisco Coutinho",
  "Rua Santa Luzia",
  "Rua Rosa Negreli",
  "Rua Matias Lobato",
  "Rua Adalgisa Ferreira dos Santos",
  "Rua A\u00edres da Cunha",
  "Rua Pol\u00f4nia",
  "Rua das Bra\u00fanas",
  "Rua Thieres Pereira Daflon",
  "Rua M\u00e1rio de Faria Soares",
  "Rua Olavo Bilac",
  "Rua Geraldo Bianchine",
  "Rua Coletora C",
  "Rua Cora Coralina",
  "Rua Santa Bernadete",
  "Rua Arist\u00f3teles Ant\u00f4nio de Souza",
  "Rua Padre Manoel da N\u00f3brega",
  "Rua Juiz Fulg\u00eancio Pimenta",
  "Rua da Jovita",
  "Rua Valentim Ant\u00f4nio Pereira",
  "Rua Abaet\u00e9",
  "Rua Dez",
  "Avenida Presidente Getulio Vargas",
  "Rua Venezuela",
  "Rua K",
  "Rua Otaviano Fabri",
  "Rua Fern\u00e3o Dias",
  "Rua Bem-Te-Vi",
  "Rua D\u00e9cima Quinta",
  "Rua 106",
  "Rua dos Sabi\u00e1s",
  "Rua Jos\u00e9 Paulo de Freitas",
  "Rua Quintino Pereira Marqu\u00eas",
  "Rua N2",
  "Rua Conselheiro Pena",
  "Rua Santa Clara",
  "Rua Tupis",
  "Rua V 9",
  "Rua Jata\u00ed",
  "Rua Henrique Faroni",
  "Rua Dona Zulmira Pereira da Silva",
  "Rua Progresso",
  "Rua Minasa",
  "Rua Divin\u00f3polis",
  "Avenida Vereador Hamilton Teodoro Guimar\u00e3es",
  "Rua das Ac\u00e1cias",
  "Rua S\u00e3o Jo\u00e3o del Rei",
  "Rua S\u00e3o Lu\u00eds",
  "Rua Lu\u00eds Ensch",
  "Rua Aroeira",
  "Rua Jos\u00e9 Neves",
  "Rua Capistrano de Abreu",
  "Rua Nove de Julho",
  "Avenida Luxemburgo",
  "Rua S\u00e3o Francisco de Assis",
  "Rua Mirai",
  "Rua Macei\u00f3",
  "Rua Eny Cabral",
  "Rua Orqu\u00eddeas",
  "Rua Monte Veneto",
  "Rua Salvador Coelho Xavier",
  "Avenida Arax\u00e1",
  "Rua Goi\u00e1s",
  "Rua O",
  "Rua Vereador Roberto Nascimento",
  "Rua Ferro",
  "Rua Equador",
  "Rua Gero Dias dos Santos",
  "Rua Sapuca\u00ed",
  "Rua Maca\u00fabas",
  "Rua Trinta e Sete",
  "Avenida Paris",
  "Rua Est\u00e1cio de S\u00e1",
  "Rua 108",
  "Rua Jo\u00e3o Apolonio Caetano",
  "Rua Moreira S\u00e1les",
  "Rua Canela",
  "Rua Sinval Coelho",
  "Rua Jenipapo",
  "Rua Joaquim Faria Salgado",
  "Rua S\u00e3o Jorge",
  "Rua do Paraguai",
  "Rua Agostinho Vieira Sim\u00f5es",
  "Rua Vinte e Um de Abril",
  "Rua S\u00e2ndalo",
  "Rua Jacare\u00edpe",
  "Rua Coronel Pedro Fernandes dos Santos",
  "Rua Mariana",
  "Rua Trinta de Janeiro",
  "Rua Dublin",
  "Rua Vitor Meireles",
  "Rua Quintino Bocaiuva",
  "Rua Liana Cabral Barbosa",
  "Rua Imburana",
  "Rua 14",
  "Rua Mouro Calisto de Miranda",
  "Rua Granito",
  "Rua Jo\u00e3o Alves de Oliveira",
  "Rua Francisco Cruz",
  "Rua Jos\u00e9 Hatem",
  "Rua da Est\u00e9r",
  "Rua S\u00e3o Domingos",
  "Rua Severo Ribeiro",
  "Rua Aimor\u00e9s",
  "Rua Turim",
  "Rua Nina Rodrigues",
  "Rua Santa Monica",
  "Rua Dois - Bairro Planalto",
  "Rua Quebra Cristal",
  "Rua da Divisa",
  "Rua Paragua\u00e7u",
  "Rua X",
  "Rua Janu\u00e1ria",
  "Avenida Santos Dumond",
  "Rua Um",
  "Rua Engenheiro Roberto Lassance",
  "Rua Jos\u00e9 de Moura",
  "Rua Santa M\u00f4nica",
  "Rua Cento e Vinte e Um",
  "Avenida Moacir Paleta",
  "Rua Ataleia",
  "Rua Flamboyantes",
  "Rua Nove",
  "Rua 06",
  "Avenida S\u00e3o Lucas",
  "Rua Leonor Neves Batista",
  "Rua Florian\u00f3polis",
  "Rua Manoel Fraga",
  "Rua Divinol\u00e2ndia",
  "Rua Raimundo Corr\u00eaa",
  "Rua Orbis Club",
  "Rua 1",
  "Rua Cantidio Ferreira Silva",
  "Rua Monte Carmelo",
  "Rua Caiubi",
  "Rua Joaquim Neves",
  "Rua Oiticica",
  "Rua Raimundo Avelino Filho",
  "Rua Professora Concei\u00e7\u00e3o Teodoro",
  "Rua Santa In\u00eas",
  "Avenida Cristiano Varela",
  "Rua Juiz de Fora",
  "Rua Dalila Cabral",
  "Rua Itapu",
  "Rua Doze",
  "Rua Dom Pedro Segundo",
  "Avenida Palmeiras Imperiais",
  "Rua Dilermando Rodrigues de Melo",
  "Rua B Dois",
  "Rua Esperan\u00e7a",
  "Rua Guapor\u00e9",
  "Rua Trinta e Tr\u00eas",
  "Rua Piracicaba",
  "Rua Bezerra de Ara\u00fajo",
  "Rua Sebasti\u00e3o Corr\u00eaa Lima",
  "Rua Jair Rodrigues Coelho",
  "Rua Porto Alegre",
  "Avenida Raimundo Alberg\u00e1ria",
  "Rua Haia",
  "Rua Quatro",
  "Rua Daniel Marcio Alves",
  "Rua Anchieta",
  "Avenida Bela Vista",
  "Rua M",
  "Rua Rond\u00f4nia",
  "Rua Sinval Leite",
  "Rua Geni Barcelos de Almeida",
  "Rua Marechal Deodoro",
  "Rua Arax\u00e1",
  "Rua Hum",
  "Rua R Dois",
  "Rua Jos\u00e9 Gon\u00e7alves Tiradentes",
  "Rua Treze de Maio",
  "Rua Estrela do Sul",
  "Rua Germana Ramalho de Oliveria",
  "Rua Irlanda",
  "Rua Sete",
  "Rua Q Dois",
  "Avenida Gr\u00e3 Duquesa de Luxemburgo",
  "Rua Azal\u00e9ia",
  "Rua Adriano Froes",
  "Rua Ivo de Tassis",
  "Rua Caxambu",
  "Avenida Martins",
  "Rua Bento Rodrigues",
  "Rua Nicolau Jos\u00e9 Gon\u00e7alves",
  "Rua Tupinamb\u00e1s",
  "Rua Emba\u00faba",
  "Rua Lindolfo Collor",
  "Rua Castro Alves",
  "Rua Dezenove",
  "Rua do Espig\u00e3o",
  "Rua Monte Gilboa",
  "Rua Dom Manoel",
  "Rua 26",
  "Rua Recife",
  "Rua W",
  "Rua Sete de Setembro",
  "Rua Calapalos",
  "Rua Pedro Muler Faria",
  "Rua Escumilha",
  "Rua 32",
  "Rua Candeia",
  "Rua Placedina Cabral",
  "Rua Sombreiro",
  "Rua 6",
  "Rua Eduardo Carlos Pereira",
  "Rua 31",
  "Rua Duarte Coelho",
  "Rua Esmeralda",
  "Rua Walter Jardim",
  "Rua da Energia",
  "Rua Ipanema",
  "Rua Iara",
  "Rua 36",
  "Rua I",
  "Rua Monte Hermon",
  "Rua Rondonia",
  "Rua Benjamin Constant",
  "Rua Am\u00e9lia Habib",
  "Rua Vaticano",
  "Rua Esc\u00f3cia",
  "Rua Vereador Omar de Magalh\u00e3es",
  "Rua Pitanga",
  "Rua Detetive Cil Farney",
  "Avenida Copacabana",
  "Avenida Presidente Kennedy",
  "Rua Martin de Souza",
  "Rua Vareda Sanit\u00e1ria",
  "Rua das Orquideas",
  "Avenida Nossa Senhora de Guadalupe",
  "Avenida Itatiaia",
  "Rua 109",
  "Rua Cianira Cortes",
  "Rua Bartolomeu Bueno",
  "Rua Veneza",
  "Rua Alb\u00e2nia",
  "Rua Dois A",
  "Rua do Cont\u00f4rno",
  "Avenida Gra Duquesa de Luxemburgo",
  "Rua Jos\u00e9 Costa Leite",
  "Rua S\u00e3o Jo\u00e3o",
  "Rua Jo\u00e3o Carlos Junior",
  "Rua Bolivia",
  "Rua Ortozia",
  "Rua Ana Nery",
  "Rua Levi Jos\u00e9 Soares",
  "Rua Monte Castelo",
  "Rua S\u00e3o Tiago Maior",
  "Rua A Dois",
  "Rua 04",
  "Rua Ant\u00f4nio Rosa Machado",
  "Rua Pedro Am\u00e9rico",
  "Rua Crisolino Ferreira da Costa",
  "Rua S\u00e3o Jo\u00e3o Batista",
  "Rua S\u00e3o Tom\u00e1s de Aquino",
  "Rua Gilson Motta Santos",
  "Rua da Conc\u00f3rdia",
  "Rua Arthur Sim\u00f5es Ramalho",
  "Rua G",
  "Rua Vicente Pereira",
  "Rua Senador Ulisses Guimaraes",
  "Rua Padre Rolin",
  "Rua Vereador Geraldo Vieira Ribeiro",
  "Rua Engenheiro Caldas",
  "Rua Santo Ant\u00f4nio do Monte",
  "Rua Curitiba",
  "Rua Janu\u00e1ria de Souza Nunes",
  "Rua Dezesseis",
  "Rua Am\u00e9rico Martins Melo",
  "Rua Prudente de Morais",
  "Rua Bar\u00e3o do Rio Branco",
  "Rua Floresta",
  "Rua Salinas",
  "Rua Jo\u00e3o Lopes da SIlva",
  "Rua Independencia",
  "Rua Carlos Dias",
  "Rua \u00c9der da Silveira",
  "Rua Adalia",
  "Rua Eliete Guedes Morais",
  "Rua Walter Vilela",
  "Rua Monte das Oliveiras",
  "Avenida Canal",
  "Rua Juiz de Paz Jos\u00e9 Lemos",
  "Rua Tr\u00eas",
  "Avenida \u00c1lvaro Reis",
  "Rua Augusto Cunha Neto",
  "Rua Ituiutaba",
  "Rua Jos\u00e9 Teodoro Delfino",
  "Rua Coridon",
  "Rua Ouro Branco",
  "Rua Divar Herckert Barbosa",
  "Rua Maria Meireles Almeida",
  "Rua Sevilha",
  "Rua Vi\u00e7osa",
  "Rua Jo\u00e3o Lopes da Silva",
  "Rua Doutor No\u00e9 Machado",
  "Avenida Coronel Pedro Ferreira",
  "Rua Milwald Alves de Lima",
  "Rua B",
  "Rua Monte Branco",
  "Rua Na\u00e7\u00f5es Santos",
  "Avenida Sebasti\u00e3o Cunha",
  "Rua J\u00falio Cipriano",
  "Rua Monte Moria",
  "Rua Ontidio S de Fraga",
  "Rua Manoel Borba Gato",
  "Rua Ss",
  "Rua S\u00e3o Jos\u00e9",
  "Rua Guaxup\u00e9",
  "Rua Para\u00edba",
  "Rua Caratinga",
  "Rua L\u00facio Alves Santana",
  "Rua Am\u00e9rico de Menezes",
  "Rua L\u00facio Lucciola",
  "Rua dos Ip\u00eas",
  "Avenida Juscelino Kubitschek",
  "Rua Monte Azul",
  "Rua Projetada",
  "Rua Padre Ant\u00f4nio Vi\u00eaira",
  "Rua M\u00f4naco",
  "Rua 34",
  "Rua Juriti",
  "Rua \u00c1guias Formosas",
  "Rua Ub\u00e1",
  "Rua Paran\u00e1",
  "Rua Virgin\u00f3polis",
  "Rua Pedro Vaz de Caminha",
  "Rua Natal",
  "Rua Manoel Batista dos Santos",
  "Rua S\u00e3o Marcos",
  "Rua Santo In\u00e1cio de Loyola",
  "Rua Jos\u00e9 Ot\u00e1vio Fonseca",
  "Rua Frutal",
  "Rua Goiatacases",
  "Rua Dores do Indai\u00e1",
  "Rua Gl\u00f3ria",
  "Rua Monte Sinai",
  "Rua Lirio do Vale",
  "Rua 116",
  "Rua da Igualdade",
  "Rua Mil\u00e3o",
  "Rua Varginha",
  "Rua Santo In\u00e1cio de Loiola",
  "Rua Francisco Sim\u00f5es Ramalho",
  "Rua Monte Elbal",
  "Rua Madre Tereza Scherer",
  "Rua Rosa Maria de Souza",
  "Rua Diamante",
  "Rua Jos\u00e9 Maria Rocha",
  "Rua 05",
  "Rua Francisco de Castro",
  "Rua Santo Agostinho",
  "Rua Emilia Goeldi",
  "Rua Vital Brasil",
  "Rua Jos\u00e9 C. Costa",
  "Rua Itamba\u00fa",
  "Rua Aracaj\u00fa",
  "Rua Pedra Azul",
  "Avenida Vereador Jos\u00e9 Fernandes",
  "Rua Airton Sena",
  "Rua dos Tupiniquins",
  "Rua Afonso Pena, 1616",
  "Rua M\u00e1rio Rocha",
  "Rua Edila Maria Soares",
  "Rua das Andorinhas",
  "Rua Vale Formoso",
  "Avenida Presidente Get\u00falio Vargas",
  "Rua Arthur Bernardes",
  "Rua Cruz e Souza",
  "Rua Termininois",
  "Rua Engenheiro Alberto Lassance",
  "Rua Joaquim Pereira Duarte",
  "Avenida Pecuarista Carlos M. Rangel",
  "Rua Miradouro",
  "Rua Pedro de Tassis",
  "Rua Francisco S\u00e1les",
  "Rua Mateus Felipe",
  "Rua Jo\u00e3o Ribeiro",
  "Rua Serra da Moeda",
  "Rua Flamboyant",
  "Rua Cec\u00edlia Siqueira",
  "Rua 35",
  "Rua Ana Neri",
  "Rua Manoel Byrro",
  "Rua Raul Soares",
  "Rua L\u00edrios do Vale",
  "Rua Araguari",
  "Rua Jos\u00e9 Roberto Guimar\u00e3es",
  "Rua Rio de Janeiro",
  "Rua Paulo de Souza Pifano",
  "Rua da Amizade",
  "Rua Frei Caneca",
  "Avenida Engenheiro \u00c1lvaro Siqueira",
  "Avenida Euzebio Cabral",
  "Rua Dinamarca",
  "Rua Particular",
  "Rua Gon\u00e7alves Dias",
  "Rua Teresina",
  "Rua Tenente Gil Pereira",
  "Rua Maria Nunes Germano",
  "Rua Primeiro de Maio",
  "Rua Agripino Ribeiro",
  "Rua Inglaterra",
  "Rua Sergipe",
  "Rua da V\u00e1rzea",
  "Rua 103",
  "Rua Henrique Lage",
  "Avenida Industrial",
  "Rua Quintiliano Costa",
  "Rua Santa Rita",
  "Rua Tarumirim",
  "Rua Heitor Veloso",
  "Rua Francisco Lemos",
  "Rua Lu\u00eds Sim\u00f5es Silva",
  "Rua Argentina",
  "Rua Sabar\u00e1",
  "Rua Fran\u00e7a",
  "Rua Diego Homaidan",
  "Rua Maria Quirino de Melo",
  "Rua Alu\u00edsio Pereira Esteves",
  "Rua do Planalto",
  "Rua Manoel Machado",
  "Rua Vista Alegre",
  "Rua Eudes Aristeu Jardim",
  "Rua Cristo Rei",
  "Avenida Mucuri",
  "Rua Nacle Miguel Habib",
  "Rua Eucaliptos",
  "Rua Carangola",
  "Rua Pav\u00e3o",
  "Rua Seringueira",
  "Rua Caio Martins",
  "Rua Ypiranga",
  "Rua Senador Milton Campos",
  "Rua B\u00e1rbara Heliodora",
  "Rua Acre",
  "Rua R",
  "Rua das Palmeiras",
  "Rua Odilon Ferreira Matos",
  "Rua Marilac",
  "Rua Maria Meireles de Almeida",
  "Rua Mem de S\u00e1",
  "Rua 13",
  "Rua Te\u00f3filo Oton\u00ed",
  "Rua E Um",
  "Rua Jo\u00e3o Rosa",
  "Rua Edgard Fernandes",
  "Rua Ranulfo Alves",
  "Rua PAra",
  "Rua Henrique Dias",
  "Rua Leopoldina",
  "Rua Mea\u00edpe",
  "Rua Paulo Frauches",
  "Rua Pitangueiras",
  "Rua Vereador Jo\u00e3o Dornelas",
  "Avenida Rio Doce",
  "Rua Leonardo Cristino",
  "Rua Monte Tragor",
  "Rua Mariana Cabral Barbosa",
  "Rua Conselheiro Lafaiete",
  "Rua da Platina",
  "Rua Benjamim Constant",
  "Rua Castanheira",
  "Rua S\u00e3o Francisco Xavier",
  "Rua Maranh\u00e3o",
  "Rua Bruxelas",
  "Rua 24",
  "Rua Manoel Moura",
  "Rua Ametista",
  "Avenida Luiz Gon\u00e7alves Lessa",
  "Rua Jo\u00e3o Maria Santos",
  "Rua Fausto Perim",
  "Rua Vereador Euzebinho Cabral",
  "Rua Vinte e Seis",
  "Rua Vereador Jos\u00e9 Domingos Vieira",
  "Rua Manoel Cordeiro da Silva",
  "Rua S\u00e9rgio Murta de Andrade",
  "Avenida Beira Rio",
  "Rua Jasmin",
  "Rua Waldeck Martins",
  "Rua Gabriel Tolentino Gon\u00e7alves",
  "Rua Arapoca",
  "Rua Monte Si\u00e3o",
  "Rua Boa Sorte",
  "Rua Santos Fernandes S\u00e1",
  "Rua 3 de Outubro",
  "Rua Cisne",
  "Rua Jos\u00e9 G. Martins",
  "Avenida Engenheiro Felipe Moreira Caldas",
  "Rua Monte Thabor",
  "Rua Uruguaiana",
  "Rua Jacaranda",
  "Rua Ja\u00edr Rodrigues Coelho",
  "Rua S\u00e3o Geraldo Magela",
  "Rua H Um",
  "Avenida do Recreio",
  "Rua Jos\u00e9 Martins de Melo",
  "Rua 02",
  "Rua da Paz",
  "Rua da Encosta",
  "Rua Gr\u00e9cia",
  "Rua Jo\u00e3o Gon\u00e7alves",
  "Rua Marinheiro de Espanha",
  "Rua G Dois",
  "Rua Cedro",
  "Rua Jos\u00e9 Lu\u00eds Nogueira",
  "Rua Marselha",
  "Rua 7",
  "Rua Oicilef Guerra",
  "Rua Jacarand\u00e1",
  "Rua Pedro Malaquias Pinto",
  "Rua dos Flamboiantes",
  "Rua Miansa",
  "Rua Joaquim Pedro Nascimento",
  "Rua Itanhomim",
  "Rua C\u00f4nego Lafaiete",
  "Rua das Ar\u00e1ras",
  "Rua S\u00e1 Carvalho",
  "Rua 20",
  "Rua Ja\u00e7an\u00e3",
  "Rua Am\u00e9rico Vesp\u00facio",
  "Rua Pavi\u00fana",
  "Rua 4",
  "Avenida Chequevaria",
  "Rua F",
  "Rua Almenara",
  "Rua 102",
  "Rua Paulo Deslandes",
  "Rua Itabirito",
  "Rua Bromelias",
  "Rua Enio Rodrigues Mourao",
  "Rua S\u00e3o Braz",
  "Rua do Angico",
  "Rua Padre Para\u00edso",
  "Rua Rouxinol",
  "Rua Frei Negreiros",
  "Rua Monte Golgota",
  "Rua Gr\u00e3o Mogol",
  "Rua Fernando Brier",
  "Rua Caviuna",
  "Rua Cl\u00e1udio Manoel",
  "Rua Piraj\u00e1",
  "Rua Ev\u00eancio Batista Coelho",
  "Avenida Gil Pacheco de Magalh\u00e3es",
  "Rua Guaruj\u00e1",
  "Rua Lavras",
  "Rua Ilda Damasceno Sim\u00f4es",
  "Rua D",
  "Rua It\u00e1lia",
  "Avenida Minas Gerais - Pista Direita",
  "Rua Cambori\u00fa",
  "Rua Edite Quint\u00e3o",
  "Rua Tup\u00e3",
  "Rua Professor Cid Pitanga",
  "Rua Osman Monteiro",
  "Rua Ju\u00edz de Fora",
  "Rua dos Pintassilgos",
  "Rua Vicente Pison",
  "Rua Ja\u00edr Avelar",
  "Rua Vinte e Oito",
  "Rua Espanha",
  "Rua Soldado Edson Veloso",
  "Rua da Cemig",
  "Avenida Distrito Industrial",
  "Rua Anastas Maraslis",
  "Rua das \u00c1guias",
  "Rua Fausto Perin",
  "Rua E",
  "Avenida Bianor de Paula Dias",
  "Rua C\u00e2ndido Portinari",
  "Rua Ant\u00f4nio Dias Adorno",
  "Rua Agenor Parreira Rocha",
  "Rua Manoel Soares dos Santos",
  "Rua Jos\u00e9 Marciano Rodrigues",
  "Rua Madri",
  "Avenida Ibituruna",
  "Rua Afonso Bretas Sobrinho",
  "Rua Doutor Altamiro Colombo Ribeiro",
  "Rua Diamantina",
  "Rua Vasco Fernandes",
  "Rua Flamboant",
  "Rua Quintino Bocai\u00fava",
  "Rua Rio Grande do Norte",
  "Rua Manhumirim",
  "Rua Afonso Pena",
  "Rua das Guianas",
  "Rua Fern\u00e3o Dias Paes Leme",
  "Rua Sabin\u00f3polis",
  "Rua Afonso Pena, 1380",
  "Rua Jos\u00e9 Ferreira de Almeida",
  "Rua L2",
  "Rua Omar Rodrigues Coelho",
  "Avenida N\u00e1poles",
  "Rua Joaquim Costa",
  "Avenida Paranaiba",
  "Avenida Mariquita",
  "Rua Virgolandia",
  "Rua Vinte e Quatro",
  "Rua Pastor Orm\u00eddio Siqueira",
  "Rua \u00c1ustria",
  "Rua Quatorze de Julho",
  "Rua S\u00e3o Jo\u00e3o del Rey",
  "Rua Anafesto Pandini",
  "Rua Nova Era",
  "Rua Duarte da Costa",
  "Rua Borba Gato",
  "Rua Copenhague",
  "Rua 38",
  "Rua Afonso Pena, 2170",
  "Rua U",
  "Rua Barcelona",
  "Rua Colombia",
  "Rua Antoniete Fernandes",
  "Rua Santa Rita de C\u00e1ssia",
  "Rua Pastoril",
  "Rua 17",
  "Rua Jos\u00e9 Lemos",
  "Rua Adolfo Perim",
  "Rua Jos\u00e9 Bicalho",
  "Rua Padre Sady Rabelo",
  "Rua Moacir de Souza",
  "Rua Juiz Jo\u00e3o Costa",
  "Rua Omar Magalh\u00e3es",
  "Rua Samuel Barbosa",
  "Rua dos Guaranis",
  "Rua das Gaivotas",
  "Rua Jos\u00e9 Tavares Pereira Filho",
  "Avenida Raimundo Albergaria",
  "Avenida S\u00e3o Paulo",
  "Rua Francisco Castro",
  "Rua Vinh\u00e1tico",
  "Rua Afonso Pena, 2356",
  "Rua B Um",
  "Rua dos Sombreiros",
  "Rua Miguel Fernandes dos Santos",
  "Avenida de Acesso",
  "Avenida Engenheiro Humberto Tavares Chagas",
  "Avenida Vertente",
  "Rua Oleg\u00e1rio Maciel",
  "Rua Eurito Orlando Bonesi",
  "Rua On\u00f3fre Dias da Silva",
  "Rua Paragua\u00e7\u00fa",
  "Rua Caet\u00e9s",
  "Rua Maria Renildes da Silva Santos",
  "Rua N",
  "Rua Rainer Barbosa",
  "Rua Jos\u00e9 Faustino Tebas",
  "Rua Campos S\u00e1les",
  "Rua Sapucaia",
  "Rua Londres",
  "Rua Luiz Lucciola",
  "Rua Adri\u00e3o Fr\u00f3es",
  "Rua Uberaba",
  "Rua Seleme Hilei",
  "Rua N\u00edquel",
  "Rua Israel Pinheiro",
  "Rua On\u00f3fre Arantes",
  "Rua Jos\u00e9 Daflon Faria",
  "Rua Viena",
  "Avenida Presidente Tancredo Neves",
  "Rua Icara\u00ed",
  "Rua Bouganvile",
  "Rua Vars\u00f3via",
  "Rua Guranis",
  "Rua Itabira",
  "Rua C\u00edcero Ciqueira",
  "Rua Temininois",
  "Avenida Sete Lagoas",
  "Rua A",
  "Rua Hungria",
  "Avenida Ferrovia",
  "Rua Treze",
  "Rua Dolardino Fioreti",
  "Rua M\u00e1rio de Faria Salgado",
  "Rua Pedro \u00c1lvares Cabral",
  "Rua Vinte e Tr\u00eas",
  "Rua Gast\u00e3o de Magalh\u00e3es",
  "Rua A Fabri",
  "Avenida Montes Claros",
  "Avenida Jequitinhonha",
  "Rua Martinho Lutero",
  "Rua Jos\u00e9 Carlos Pereira",
  "Rua Barroso Guimar\u00e3es",
  "Avenida Alto Sir",
  "Rua Euz\u00e9bio Martins Silva",
  "Rua Osvaldo Cruz",
  "Rua O Dois",
  "Rua Ant\u00f4nio Frois",
  "Rua Jo\u00e3o de Barro",
  "Rua Grevile",
  "Rua Y",
  "Rua Luiz Ensch",
  "Rua V",
  "Avenida Carlos Gomes",
  "Rua Cavi\u00fana",
  "Rua Euclides da Cunha",
  "Rua Bocaina",
  "Rua Manoel Codeiro da Silva",
  "Rua Ant\u00f4nio Ferreira da Silva",
  "Rua Jos\u00e9 Gon\u00e7alves de Sena",
  "Rua da Justica",
  "Rua Cl\u00f3vis de Souza",
  "Rua Geraldo Ribeiro",
  "Rua do Frigor\u00edfico",
  "Rua Raffy Amim Zaidan",
  "Rua \u00c2ngelo Venturi Magrini",
  "Rua Alto Sir",
  "Rua Santa Rosa",
  "Rua Pe\u00e7anha",
  "Rua Apgaua Paulo Guilherme",
  "Rua Lopes de Souza",
  "Rua do Semin\u00e1rio",
  "Rua Vinte e Cinco",
  "Rua Arthur Bernardes, 517",
  "Rua Monte Pascoal",
  "Avenida da Lagoa",
  "Rua Alcino Nunes Germano",
  "Rua Marcos V. de Carvalho",
  "Rua Um A",
  "Rua Coronel Roberto Soares Ferreira",
  "Avenida Carandai",
  "Rua Su\u00ed\u00e7a",
  "Rua Cear\u00e1",
  "Rua Israel Pinheiro, 1212",
  "Rua Manaca",
  "Rua Lagoa Santa",
  "Rua Alemanha",
  "Rua Espera Feliz",
  "Rua Par\u00e1",
  "Rua da Independ\u00eancia",
  "Rua Nova Lima",
  "Avenida Minas Gerais",
  "Rua Ant\u00f4nio Guilherme Sobrinho",
  "Rua das Oliveiras",
  "Rua Dinah Ribeiro",
  "Rua Andrel\u00e2ndia",
  "Rua Inconfid\u00eancia",
  "Rua Itajuba",
  "Rua Joaquim Ribeiro Nascimento",
  "Rua Galil\u00e9ia",
  "Rua Padre Sadi Rab\u00ealo",
  "Rua J\u00falio Ferreira de Almeida",
  "Rua Paraju",
  "Rua Arguari",
  "Rua Bra\u00fanas",
  "Rua Santa F\u00e9",
  "Rua Rodrigues Alves",
  "Rua Azaleias",
  "Rua Pouso Alegre",
  "Rua Santo Estev\u00e3o",
  "Rua Ant\u00f4nio Figueiredo Froes",
  "Rua Jos\u00e9 Dias da Silva",
  "Rua Coromandel",
  "Rua Altamiro Guilherme",
  "Rua Bocai\u00fava",
  "Rua Jorge Figueiredo",
  "Rua Graviola",
  "Rua Sebasti\u00e3o Ac\u00e1cio",
  "Rua Sacramento",
  "Rua Angelim",
  "Rua S",
  "Rua Proj. Mae de Deus",
  "Rua Berilo",
  "Rua Zumbi",
  "Rua S\u00e3o Sim\u00e3o",
  "Rua Pirapora",
  "Rua Queluz",
  "Rua Holanda",
  "Rua Turmalina",
  "Rua Doutor Jo\u00e3o Fernandes Le\u00e3o",
  "Rua Ribeiro Junqueira",
  "Rua Bra\u00fana",
  "Rua Jos\u00e9 Maciel",
  "Rua Yp\u00ea",
  "Rua Jos\u00e9 Gomes da Silva",
  "Rua Palermo",
  "Rua L",
  "Rua Cecil Rodrigues Coelho",
  "Rua Magn\u00f3lia",
  "Rua Jo\u00e3o Agripino Mendes",
  "Rua Jo\u00e3o Paulo Pinheiro",
  "Rua Manoel Bandeira",
  "Avenida Gr\u00e3 Duqueza de Luxemburgo",
  "Rua Jos\u00e9 Ot\u00e1vio da Fonseca",
  "Rua Unai",
  "Rua Humberto Nazareth",
  "Rua Al\u00e9m Para\u00edba",
  "Rua Amap\u00e1",
  "Rua G1",
  "Rua Am\u00e9rico Martins de Melo",
  "Rua Leila Cabral",
  "Rua Noruega",
  "Avenida Barbosa Rodrigues",
  "Rua Rodolfo de Abreu",
  "Rua Lagoa da Prata",
  "Rua Carlos Chagas",
  "Avenida Gr\u00e3 Duquesa",
  "Rua dos Aimor\u00e9s",
  "Rua dos Org\u00e3os",
  "Rua Ac\u00e1cia",
  "Rua 33",
  "Rua Cinquenta e Oito",
  "Rua Raimundo Luzia da Silveira",
  "Rua Don\u00e1 Zulmira Pereira da Silva",
  "Rua Poti",
  "Rua Manaus",
  "Avenida da Vertente",
  "Rua Beija Flor",
  "Rua Minas Novas",
  "Rua Tumiritinga",
  "Rua Quinze de Novembro",
  "Rua Vereador Adriano Silva",
  "Avenida do Canal",
  "Rua Coromandeu",
  "Rua Berlim",
  "Rua 117",
  "Rua Santa Tereza",
  "Rua Jo\u00e3o Denizar",
  "Rua Adel Couto",
  "Rua Guarapari",
  "Rua Ruth Cabral",
  "Rua Dalia",
  "Rua Sinval Rodrigues Coelho",
  "Rua Cobre",
  "Rua Santa B\u00e1rbara",
  "Rua Macabu",
  "Rua das Bandeiras",
  "Rua Vinte e Um",
  "Rua Manga",
  "Rua 112",
  "Rua 10",
  "Rua Primeiro de Janeiro",
  "Avenida C",
  "Rua S\u00e3o Bartolomeu",
  "Rua 21 de Abril",
  "Rua 107",
  "Rua Oitava",
  "Rua Palma",
  "Rua dos Carij\u00f3s",
  "Rua Gabriel Gon\u00e7alves da Silva",
  "Rua Oto Nunes Coelho",
  "Rua Viela Sanit\u00e1ria Tr\u00eas",
  "Rua Seis",
  "Rua Zelinda Chieste",
  "Rua 101",
  "Rua Itanhomi",
  "Rua Marata\u00edzes",
  "Rua Nossa Senhora de Lourdes",
  "Rua \u00c1lamo",
  "Rua S\u00e3o Louren\u00e7o",
  "Avenida Doutor Luiz de Sousa Lima",
  "Rua L\u00edrio Cabral",
  "Avenida Tiradentes",
  "Rua Geraldo dos Santos",
  "Rua Monte Alto",
  "Avenida Washington Lu\u00eds",
  "Rua Padre Leonardo Senne",
  "Rua Santo On\u00f3fre",
  "Rua Eni Cabral",
  "Avenida Coletora A",
  "Rua Granada",
  "Rua Bartolomeu Dias",
  "Rua Santos Dumont",
  "Rua Serra Negra",
  "Rua Pinheiro",
  "Rua das Quaresmeiras",
  "Avenida Um",
  "Rua Gentil Dias da Silva",
  "Rua da Passagem",
  "Rua Setenta e Sete",
  "Rua Serra da Mantiqueira",
  "Rua Coimbra",
  "Rua Par\u00e1 de Minas",
  "Rua S\u00e3o Judas Tadeu",
  "Rua Ant\u00f4nio Jos\u00e9 de Almeida",
  "Rua Francisco de Paula Freitas",
  "Rua Pero Vaz de Caminha",
  "Rua Esplanada",
  "Rua Doze de Outubro",
  "Avenida Dois",
  "Rua Eucl\u00eddes Sabino dos Santos",
  "Rua dos Flamboyants",
  "Rua Sapucai",
  "Rua dos Terminiois",
  "Rua Ibituruna",
  "Rua S\u00e3o Paulo",
  "Rua Pernambuco",
  "Rua Paulo Neves",
  "Rua 142",
  "Rua dos Tam\u00f4ios",
  "Avenida da Vazante",
  "Rua Piunbi",
  "Rua S\u00e3o Pedro",
  "Avenida Manoel de Souza Neto",
  "Rua da Pedreira",
  "Rua S\u00edlvio Rom\u00e9rio",
  "Rua Ficus",
  "Rua Joaquim Neves Ferreira",
  "Rua Cerejeira",
  "Avenida Minas Gerais - Pista Esquerda",
  "Rua 114",
  "Rua Sic\u00edlia",
  "Rua Helton H\u00e9lio Quint\u00e3o",
  "Avenida Diva Erthal Collier",
  "Rua Marechal Floriano",
  "Rua Amazonas",
  "Avenida Nacle Miguel Habib",
  "Rua Angico",
  "Rua Oliveira",
  "Rua Germana Ramalho",
  "Rua Jos\u00e9 H. Deslandes",
  "Rua Rui Barbosa",
  "Rua Davidson Araujo",
  "Rua Cl\u00e1udio Nunes Leite",
  "Rua Jatoba",
  "Rua Fern\u00e3o de Magalh\u00e3es",
  "Rua da Gruta",
  "Rua 111",
  "Rua Erasmo Braga",
  "Rua Nanuque",
  "Rua D\u00e9cima Terceira",
  "Rua Dona Jovita",
  "Rua Augusto dos Anjos",
  "Rua P",
  "Rua Monte Seir",
  "Rua Geraldino Barbosa Pimenta",
  "Rua Divisa",
  "Rua Altino Caetano",
  "Rua Samuel Gamon",
  "Rua Geraldo Coelho de Magalhaes",
  "Rua Vinte",
  "Rua Jo\u00e3o Batista de Oliveira",
  "Rua Jos\u00e9 de Tassis",
  "Rua Ita\u00fana",
  "Rua Ilda Damasceno Sim\u00f5es",
  "Rua Colombita",
  "Rua Santo Ant\u00f4nio",
  "Rua Agata",
  "Rua Paulo Sendas",
  "Rua Passos",
  "Rua Adriano Vicente",
  "Rua Am\u00e1vel Soares",
  "Rua Ouro Preto",
  "Rua Vereador Omar de Magalhaes",
  "Rua Felipe Camar\u00e3o",
  "Rua Tomaz Ant\u00f4nio Gonzaga",
  "Rua Arthur Brand\u00e3o",
  "Rua Cinco",
  "Rua Porto Seguro",
  "Rua das Esmeraldas",
  "Rua Vinte e Nove",
  "Rua Dois",
  "Rua Bulg\u00e1ria",
  "Rua 115",
  "Rua Sanit\u00e1ria",
  "Rua Thieres Pereira Dafdlon Farias",
  "Rua 3",
  "Rua Ouro Fino",
  "Rua Almyr Baptista de Souza",
  "Rua N\u00edzio Pe\u00e7anha Barcelos",
  "Rua Carijos",
  "Rua Q",
  "Rua Joaquim Francisco de Souza",
  "Rua \u00c1lvaro Reis",
  "Rua das Margaridas",
  "Rua Baependi",
  "Rua Caramuru",
  "Rua Piau\u00ed",
  "Rua L\u00edbano",
  "Rua Estocolmo",
  "Rua Z",
  "Rua 16",
  "Avenida Presidente Castelo Branco",
  "Rua Itapija",
  "Rua Corinto",
  "Rua Canal",
  "Rua Luiz Gonzaga da Rocha e Silva",
  "Rua 22",
  "Avenida do Ipiranga",
  "Rua Fagundes Varela",
  "Rua G\u00eanova",
  "Rua Gonzaga",
  "Rua Samuel Moura",
  "Rua Artur Foranttini",
  "Rua Oitis",
  "Rua Esp\u00edrito Santo",
  "Rua \u00c2ngico",
  "Rua da Mica",
  "Avenida dos Lagos",
  "Rua D Um",
  "Rua Afonso Pena, 1916",
  "Rua Talco",
  "Rua Noel Rosa",
  "Rua Jos\u00e9 Pedro Clementino",
  "Rua Margarida",
  "Rua Congonhas",
  "Avenida Suassui",
  "Rua Jasmins",
  "Rua Curvelo",
  "Rua 19",
  "Rua Manoel Birro",
  "Rua Anastas Maralis",
  "Rua Serra da Canastra",
  "Rua Paulo Bezerra Lopes",
  "Rua 29",
  "Rua Paracatu",
  "Rua J",
  "Rua Lilia Cabral Costa",
  "Rua do Zinco",
  "Rua Monte Calvo",
  "Rua Jos\u00e9 do Patroc\u00ednio",
  "Rua Peroba",
  "Rua Campos Sales",
  "Avenida Padre Jos\u00e9 Manoel da Concei\u00e7\u00e3o",
  "Rua dos Flamboyantes",
  "Rua Sapuc\u00e1ia",
  "Rua Cristal",
  "Avenida Jacare\u00edpe",
  "Rua Beco 1",
  "Rua Guanh\u00e3es",
  "Avenida Brom\u00e9lias",
  "Rua Fern\u00e3o de Andrade",
  "Rua S\u00e3o Sebasti\u00e3o",
  "Rua Xavantes",
  "Rua Gon\u00e7alo Costa",
  "Rua Alfredo Gomes Silva",
  "Rua Rubim",
  "Avenida 105",
  "Rua Jos\u00e9 Ferreira",
  "Rua 8",
  "Rua dos Rouxin\u00f3is",
  "Avenida Coqueiral",
  "Rua das Gar\u00e7as",
  "Rua Paulino Rodrigues",
  "Avenida Rio Doce - Bairro S\u00e3o Paulo",
  "Rua Ivaldo Tassis",
  "Rua Alvarenga Peixoto",
  "Rua Gra\u00e7a Aranha",
  "Rua Juvenal Batista",
  "Rua Jos\u00e9 Lu\u00eds Santos",
  "Rua Bel\u00e9m",
  "Rua Carvalho",
  "Rua Francisco Caetano Pimentel",
  "Rua Belo Horizonte",
  "Avenida 100",
  "Rua Jos\u00e9 Augusto da Silva",
  "Rua da Miseric\u00f3rdia",
  "Rua Dona Aurita Rodrigues Rocha",
  "Avenida Lisboa",
  "Rua Caja",
  "Rua Tenente Coronel Francisco Fernandes",
  "Rua C\u00edcero Siqueira",
  "Rua Visconde de Mau\u00e1",
  "Rua Elza Guimar\u00e3es",
  "Rua Am\u00e9lio Melga\u00e7o",
  "Rua Trinta e Quatro",
  "Rua S\u00e3o Lucas",
  "Rua Expedito Ferreira de Carvalho",
  "Rua 2",
  "Rua Uberl\u00e2ndia",
  "Rua Cento e Trinta e Sete",
  "Rua Raimundo da Silveira",
  "Avenida Divin\u00f3polis",
  "Rua Epit\u00e1cio Pessoa",
  "Rua Clotildes Alvarenga",
  "Rua Henrique Bahia",
  "Rua Otoniel Mota",
  "Rua Caipo",
  "Rua Hermes Pimenta",
  "Rua 18",
  "Rua Roquete Pinto",
  "Avenida Anhang\u00fcera",
  "Rua Sebasti\u00e3o Gomes",
  "Rua Lambari",
  "Rua Hematita",
  "Rua Luxemburgo",
  "Rua Rosa Aguiar",
  "Rua da Bahia",
  "Rua Perd\u00f5es",
  "Rua Geraldo Vieira",
  "Rua Apatita",
  "Rua Sucupira",
  "Rua Gilson Motta",
  "Rua Atenas",
  "Rua Trinta",
  "Rua Hamburgo",
  "Rua 03",
  "Rua Santa Catarina",
  "Rua Martim Lutero",
  "Rua Top\u00e1zio",
  "Rua B\u00e9lgica",
  "Rua Bicuiba",
  "Avenida Santos Dumont",
  "Rua Monte Nebo",
  "Rua Tom\u00e9 de Souza",
  "Rua Miguel Couto",
  "Rua Darcy Martins dos Santos",
  "Rua Quartzo",
  "Rua 9",
  "Rua Jacinto",
  "Rua Rio Preto",
  "Rua Olane Tavares Pereira",
  "Avenida Presidente Kenedy",
  "Rua Jos\u00e9 de Abreu",
  "Rua Pedro Lessa",
  "Rua Parajara dos Santos",
  "Rua Jos\u00e9 Malvino",
  "Avenida Bruno Chaves",
  "Rua Maria Cecilia Moreira",
  "Rua Oiti",
  "Rua Doutor Paulo de Sousa Lima",
  "Rua Carlos Drumond de Andrade",
  "Avenida Coletora B",
  "Rua Marta Gon\u00e7alves Reis",
  "Rua Tom Jobim",
  "Rua Matatias Gomes",
  "Rua do Recreio",
  "Rua Jos\u00e9 Oliveira de Andrade",
  "Rua Braunas",
  "Rua Cec\u00edlia Meireles",
  "Avenida Professor Sinval Silva",
  "Rua Alto da Boa Vista",
  "Rua Jo\u00e3o Pessoa",
  "Avenida Capara\u00f3",
  "Rua das Acassias",
  "Rua Artur Brandao",
  "Rua Oito",
  "Rua Ant\u00f4nio Trajano",
  "Rua 28",
  "Rua Maontevideu",
  "Rua Professor Jos\u00e9 de Carvalho",
  "Rua Hildebrando Cabral",
  "Rua Manoel de Abreu",
  "Rua Chile",
  "Rua Dezoito",
  "Rua Ara\u00e7ua\u00ed",
  "Rua Perdizes",
  "Rua Prata",
  "Rua Luc\u00edlia Coelho do Amaral",
  "Rua dos Paulistas",
  "Rua Sibipuruna",
  "Rua Beirute",
  "Rua Inhapim",
  "Rua S\u00e3o Mateus",
  "Avenida do Acesso",
  "Avenida Vezena",
  "Rua Ponte Nova",
  "Rua Safira",
  "Rua 5",
  "Rua Barbosa Rodrigues",
  "Rua Rio Grande do Sul",
  "Rua Apolin\u00e1rio Satlher",
  "Avenida JK",
  "Rua Uni\u00e3o",
  "Rua Padre Anchieta",
  "Avenida Beira Lago",
  "Rua Geraldo Daflon",
  "Rua Vasco da Gama",
  "Rua Guaran\u00eds",
  "Rua Boa Vista",
  "Rua Vinte e Dois de Abril",
  "Rua Esmeraldas",
  "Avenida Guanabara",
  "Rua Jequitiba",
  "Rua Santo Sebasti\u00e3o",
  "Rua Itambacuri",
  "Rua Coroacif",
  "Avenida Simonton",
  "Rua Pascoal de Souza Lima",
  "Rua da Fraternidade",
  "Rua Manhua\u00e7u",
  "Rua Conjunto Habitacional",
  "Rua Nossa Senhora Aparecida",
  "Rua Virg\u00edlio Gobi",
  "Rua Onze",
  "Avenida Gilardi Pach\u00eaco de Magalh\u00e3es",
  "Avenida Po\u00e7os de Caldas",
  "Avenida A",
  "Rua Buen\u00f3polis",
  "Rua Tr\u00eas Cora\u00e7\u00f5es",
  "Rua Pau Brasil",
  "Rua Quinze",
  "Rua Jos\u00e9 Ver\u00edssimo",
  "Avenida Dois de Julho",
  "Rua Barbacena",
  "Rua Floren\u00e7a",
  "Avenida S\u00e3o Francisco",
  "Rua Paulo Deslande",
  "Rua Mogno",
  "Rua Benjamin Rodrigues Coelho",
  "Rua Neuza do Val Ramos",
  "Rua Maraj\u00e1",
  "Avenida Lucilia de Abreu Cabral",
  "Rua Didi Barra",
  "Rua Todos os Santos",
  "Avenida Agenor Andrade",
  "Rua Su\u00e9cia",
  "Rua Mato Grosso",
  "Rua Machado de Assis",
  "Rua Dezessete",
  "Rua S\u00e3o Salvador",
  "Rua Jos\u00e9 Aparecido Ramirez",
  "Rua Quatorze",
  "Rua Jo\u00e3o Calvino"
]